/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tk2_klmpk5;

/**
 *
 * @author NADIRA
 */
public class mainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainFrame.class.getName());

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tMotor = new javax.swing.JButton();
        tMobil = new javax.swing.JButton();
        tSepeda = new javax.swing.JButton();
        tPesawat = new javax.swing.JButton();
        tBus = new javax.swing.JButton();
        tTruk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tMotor.setText("Motor");
        tMotor.addActionListener(this::tMotorActionPerformed);

        tMobil.setText("Mobil");
        tMobil.addActionListener(this::tMobilActionPerformed);

        tSepeda.setText("Sepeda");
        tSepeda.addActionListener(this::tSepedaActionPerformed);

        tPesawat.setText("Pesawat");
        tPesawat.addActionListener(this::tPesawatActionPerformed);

        tBus.setText("Bus");
        tBus.addActionListener(this::tBusActionPerformed);

        tTruk.setText("Truk");
        tTruk.addActionListener(this::tTrukActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tBus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(224, 224, 224)
                        .addComponent(tTruk, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tSepeda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tPesawat))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tMotor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tMobil)))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tMotor)
                    .addComponent(tMobil))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tSepeda)
                    .addComponent(tPesawat))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tBus)
                    .addComponent(tTruk))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMotorActionPerformed
        // TODO add your handling code here:
        new FrameMotor().setVisible(true);
    }//GEN-LAST:event_tMotorActionPerformed

    private void tMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMobilActionPerformed
        // TODO add your handling code here:
        new frameMobil().setVisible(true);
    }//GEN-LAST:event_tMobilActionPerformed

    private void tPesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPesawatActionPerformed
        // TODO add your handling code here:
        new FramePesawat().setVisible(true);
    }//GEN-LAST:event_tPesawatActionPerformed

    private void tSepedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSepedaActionPerformed
        // TODO add your handling code here:
        new FrameSepeda().setVisible(true);
    }//GEN-LAST:event_tSepedaActionPerformed

    private void tBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBusActionPerformed
        // TODO add your handling code here:
        new FrameBus().setVisible(true);
    }//GEN-LAST:event_tBusActionPerformed

    private void tTrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTrukActionPerformed
        // TODO add your handling code here:
        new FrameTruk().setVisible(true);
    }//GEN-LAST:event_tTrukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton tBus;
    private javax.swing.JButton tMobil;
    private javax.swing.JButton tMotor;
    private javax.swing.JButton tPesawat;
    private javax.swing.JButton tSepeda;
    private javax.swing.JButton tTruk;
    // End of variables declaration//GEN-END:variables
}
