/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tk2_klmpk5.views;
import tk2_klmpk5.model.Login;

/**
 *
 * @author NADIRA
 */
public class mainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainFrame.class.getName());

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        Login lg = new Login();
        lUser.setText(lg.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bMotor = new javax.swing.JButton();
        bSepeda = new javax.swing.JButton();
        bBus = new javax.swing.JButton();
        bMobil = new javax.swing.JButton();
        bPesawat = new javax.swing.JButton();
        bTruk = new javax.swing.JButton();
        lUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("KENDARAAN");

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pilih Jenis Kendaraan Untuk Melihat Informasi");

        bMotor.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 1, 18)); // NOI18N
        bMotor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_klmpk5/icon/Group 1.png"))); // NOI18N
        bMotor.setText("     Motor");
        bMotor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bMotor.addActionListener(this::bMotorActionPerformed);

        bSepeda.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 1, 18)); // NOI18N
        bSepeda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_klmpk5/icon/Group 5.png"))); // NOI18N
        bSepeda.setText("      Sepeda");
        bSepeda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSepeda.addActionListener(this::bSepedaActionPerformed);

        bBus.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 1, 18)); // NOI18N
        bBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_klmpk5/icon/Group 7.png"))); // NOI18N
        bBus.setText("        Bus");
        bBus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBus.addActionListener(this::bBusActionPerformed);

        bMobil.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 1, 18)); // NOI18N
        bMobil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_klmpk5/icon/Group 3.png"))); // NOI18N
        bMobil.setText("          Mobil");
        bMobil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bMobil.addActionListener(this::bMobilActionPerformed);

        bPesawat.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 1, 18)); // NOI18N
        bPesawat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_klmpk5/icon/Group 9.png"))); // NOI18N
        bPesawat.setText("         Pesawat");
        bPesawat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bPesawat.addActionListener(this::bPesawatActionPerformed);

        bTruk.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 1, 18)); // NOI18N
        bTruk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_klmpk5/icon/Group 11.png"))); // NOI18N
        bTruk.setText("          Truk");
        bTruk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bTruk.addActionListener(this::bTrukActionPerformed);

        lUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tk2_klmpk5/icon/User.png"))); // NOI18N
        lUser.setText("------");
        lUser.setDisabledIcon(null);
        lUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lUser.setIconTextGap(20);
        lUser.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lUserAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bMotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bSepeda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bBus, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bMobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bTruk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bPesawat, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lUser, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bMobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bMotor, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bPesawat, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(bSepeda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bBus, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(bTruk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMotorActionPerformed
        // TODO add your handling code here:
        new FrameMotor().setVisible(true);
    }//GEN-LAST:event_bMotorActionPerformed

    private void bSepedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSepedaActionPerformed
        // TODO add your handling code here:
        new FrameSepeda().setVisible(true);
    }//GEN-LAST:event_bSepedaActionPerformed

    private void bMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMobilActionPerformed
        // TODO add your handling code here:
        new frameMobil().setVisible(true);
    }//GEN-LAST:event_bMobilActionPerformed

    private void bPesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesawatActionPerformed
        // TODO add your handling code here:
        new FramePesawat().setVisible(true);
    }//GEN-LAST:event_bPesawatActionPerformed

    private void bBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBusActionPerformed
        // TODO add your handling code here:
        new FrameBus().setVisible(true);
    }//GEN-LAST:event_bBusActionPerformed

    private void bTrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTrukActionPerformed
        // TODO add your handling code here:
        new FrameTruk().setVisible(true);
    }//GEN-LAST:event_bTrukActionPerformed

    private void lUserAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lUserAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lUserAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBus;
    private javax.swing.JButton bMobil;
    private javax.swing.JButton bMotor;
    private javax.swing.JButton bPesawat;
    private javax.swing.JButton bSepeda;
    private javax.swing.JButton bTruk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lUser;
    // End of variables declaration//GEN-END:variables
}
